// Mocks generated by Mockito 5.4.4 from annotations
// in flow/test/helpers/test_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flow/core/errors/failures.dart' as _i7;
import 'package:flow/core/network/network_info.dart' as _i11;
import 'package:flow/core/usecases/usecase.dart' as _i8;
import 'package:flow/features/todo/data/datasources/todo_local_datasource.dart'
    as _i10;
import 'package:flow/features/todo/data/datasources/todo_remote_datasource.dart'
    as _i9;
import 'package:flow/features/todo/domain/entities/todo.dart' as _i3;
import 'package:flow/features/todo/domain/repositories/todo_repository.dart'
    as _i5;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTodo_1 extends _i1.SmartFake implements _i3.Todo {
  _FakeTodo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_2 extends _i1.SmartFake implements Duration {
  _FakeDuration_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressCheckResult_3 extends _i1.SmartFake
    implements _i4.AddressCheckResult {
  _FakeAddressCheckResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i5.TodoRepository {
  @override
  _i6.Future<_i2.Either<_i7.Failure, List<_i3.Todo>>> getTodos() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodos,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, List<_i3.Todo>>>.value(
            _FakeEither_0<_i7.Failure, List<_i3.Todo>>(
          this,
          Invocation.method(
            #getTodos,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, List<_i3.Todo>>>.value(
                _FakeEither_0<_i7.Failure, List<_i3.Todo>>(
          this,
          Invocation.method(
            #getTodos,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, List<_i3.Todo>>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i3.Todo>> getTodoById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodoById,
          [id],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i3.Todo>>.value(
            _FakeEither_0<_i7.Failure, _i3.Todo>(
          this,
          Invocation.method(
            #getTodoById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i3.Todo>>.value(
                _FakeEither_0<_i7.Failure, _i3.Todo>(
          this,
          Invocation.method(
            #getTodoById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i3.Todo>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>> addTodo(_i3.Todo? todo) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [todo],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
            _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #addTodo,
            [todo],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
                _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #addTodo,
            [todo],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>> updateTodo(
          _i3.Todo? todo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todo],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
            _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #updateTodo,
            [todo],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
                _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #updateTodo,
            [todo],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>> deleteTodoById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTodoById,
          [id],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
            _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #deleteTodoById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
                _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #deleteTodoById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>> deleteAllTodos() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllTodos,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
            _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #deleteAllTodos,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
                _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #deleteAllTodos,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>> deleteCompletedTodos() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCompletedTodos,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
            _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #deleteCompletedTodos,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
                _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #deleteCompletedTodos,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>> markTodoAsCompleted(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markTodoAsCompleted,
          [id],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
            _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #markTodoAsCompleted,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
                _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #markTodoAsCompleted,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>);

  @override
  _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>> markTodoAsIncompleted(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #markTodoAsIncompleted,
          [id],
        ),
        returnValue: _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
            _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #markTodoAsIncompleted,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>.value(
                _FakeEither_0<_i7.Failure, _i8.NoParams>(
          this,
          Invocation.method(
            #markTodoAsIncompleted,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i7.Failure, _i8.NoParams>>);
}

/// A class which mocks [TodoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRemoteDataSource extends _i1.Mock
    implements _i9.TodoRemoteDataSource {
  @override
  _i6.Future<List<_i3.Todo>> getTodos() => (super.noSuchMethod(
        Invocation.method(
          #getTodos,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Todo>>.value(<_i3.Todo>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.Todo>>.value(<_i3.Todo>[]),
      ) as _i6.Future<List<_i3.Todo>>);

  @override
  _i6.Future<_i3.Todo> getTodoById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTodoById,
          [id],
        ),
        returnValue: _i6.Future<_i3.Todo>.value(_FakeTodo_1(
          this,
          Invocation.method(
            #getTodoById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Todo>.value(_FakeTodo_1(
          this,
          Invocation.method(
            #getTodoById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.Todo>);

  @override
  _i6.Future<void> addTodo(_i3.Todo? todo) => (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [todo],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateTodo(_i3.Todo? todo) => (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todo],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTodoById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoById,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllTodos,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCompletedTodos() => (super.noSuchMethod(
        Invocation.method(
          #deleteCompletedTodos,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markTodoAsCompleted(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markTodoAsCompleted,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markTodoAsIncompleted(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markTodoAsIncompleted,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [TodoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoLocalDataSource extends _i1.Mock
    implements _i10.TodoLocalDataSource {
  @override
  _i6.Future<List<_i3.Todo>> getTodos() => (super.noSuchMethod(
        Invocation.method(
          #getTodos,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Todo>>.value(<_i3.Todo>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.Todo>>.value(<_i3.Todo>[]),
      ) as _i6.Future<List<_i3.Todo>>);

  @override
  _i6.Future<void> cacheTodos(List<_i3.Todo>? todos) => (super.noSuchMethod(
        Invocation.method(
          #cacheTodos,
          [todos],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.Todo> getTodoById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTodoById,
          [id],
        ),
        returnValue: _i6.Future<_i3.Todo>.value(_FakeTodo_1(
          this,
          Invocation.method(
            #getTodoById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.Todo>.value(_FakeTodo_1(
          this,
          Invocation.method(
            #getTodoById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.Todo>);

  @override
  _i6.Future<void> addTodo(_i3.Todo? todo) => (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [todo],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateTodo(_i3.Todo? todo) => (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todo],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTodoById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoById,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllTodos,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCompletedTodos() => (super.noSuchMethod(
        Invocation.method(
          #deleteCompletedTodos,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markTodoAsCompleted(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markTodoAsCompleted,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markTodoAsIncompleted(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markTodoAsIncompleted,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  @override
  _i6.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i4.InternetConnectionChecker {
  @override
  Duration get checkInterval => (super.noSuchMethod(
        Invocation.getter(#checkInterval),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkInterval),
        ),
        returnValueForMissingStub: _FakeDuration_2(
          this,
          Invocation.getter(#checkInterval),
        ),
      ) as Duration);

  @override
  Duration get checkTimeout => (super.noSuchMethod(
        Invocation.getter(#checkTimeout),
        returnValue: _FakeDuration_2(
          this,
          Invocation.getter(#checkTimeout),
        ),
        returnValueForMissingStub: _FakeDuration_2(
          this,
          Invocation.getter(#checkTimeout),
        ),
      ) as Duration);

  @override
  List<_i4.AddressCheckOptions> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i4.AddressCheckOptions>[],
        returnValueForMissingStub: <_i4.AddressCheckOptions>[],
      ) as List<_i4.AddressCheckOptions>);

  @override
  set addresses(List<_i4.AddressCheckOptions>? value) => super.noSuchMethod(
        Invocation.setter(
          #addresses,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i4.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i6.Future<_i4.InternetConnectionStatus>.value(
            _i4.InternetConnectionStatus.connected),
        returnValueForMissingStub:
            _i6.Future<_i4.InternetConnectionStatus>.value(
                _i4.InternetConnectionStatus.connected),
      ) as _i6.Future<_i4.InternetConnectionStatus>);

  @override
  _i6.Stream<_i4.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i6.Stream<_i4.InternetConnectionStatus>.empty(),
        returnValueForMissingStub:
            _i6.Stream<_i4.InternetConnectionStatus>.empty(),
      ) as _i6.Stream<_i4.InternetConnectionStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isActivelyChecking => (super.noSuchMethod(
        Invocation.getter(#isActivelyChecking),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<_i4.AddressCheckResult> isHostReachable(
          _i4.AddressCheckOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [options],
        ),
        returnValue:
            _i6.Future<_i4.AddressCheckResult>.value(_FakeAddressCheckResult_3(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AddressCheckResult>.value(_FakeAddressCheckResult_3(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
      ) as _i6.Future<_i4.AddressCheckResult>);
}
